### ISSUE TITLE
Error #500

### ISSUE THREAD

**Issue by murakamiiii** [Ambiwlans/EnKen#1]
It keep showing this error message when i pressed "know it" or "don't know"
![image](https://user-images.githubusercontent.com/84261861/205955408-fe423a8a-bd17-4af5-bd4d-be23087d3fb7.png)

**Comment by Ambiwlans** [comment]
If you go to https://entest.fly.dev/ directly, it should work. It is trying to load data from the old server. Will try to fix it tomorrow. Thanks for the message!

**Comment by Ambiwlans** [comment]
Should be fixed now. The redirect was adding a frame i didn't notice which broke the url.

Feel free to post any further issues or ideas. Jiken/enken aren't top priority atm, but I'm always happy to improve them, time willing.
